### ISSUE TITLE
ARM: java.io.IOException FAILED_TO_UNCOMPRESS

### ISSUE THREAD

**Issue by blenessy** [radixdlt/node-runner#18]
An ARM (arm64v8) node (85.93.213.19) is trying to join the alphanet2 network. However the snappy compressor seems to be corrupt because we get the following Error on one of the *boot* nodes it is trying to connect with:

2019-03-25T12:43:06.576807637Z 12 43:06,545 ERROR: [general] l:322 - UDP /85.93.213.19 error
2019-03-25T12:43:06.576820437Z java.io.IOException FAILED_TO_UNCOMPRESS(5)
2019-03-25T12:43:06.576855437Z  at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98)
2019-03-25T12:43:06.576929638Z  at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
2019-03-25T12:43:06.577007938Z  at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:474)
2019-03-25T12:43:06.577097039Z  at org.xerial.snappy.Snappy.uncompress(Snappy.java:513)
2019-03-25T12:43:06.577221739Z  at org.xerial.snappy.Snappy.uncompress(Snappy.java:488)
2019-03-25T12:43:06.577307840Z  at org.radix.h.m.a.t(SourceFile:59)
2019-03-25T12:43:06.577390540Z  at org.radix.h.l.run(SourceFile:317)
2019-03-25T12:43:06.577472941Z  at java.lang.Thread.run(Thread.java:748)

**Comment by blenessy** [comment]
`radixdlt/radixdlt-core:alphanet2` images are updated with new RadixCore (version: `0.250.991`) which contains the following fixed of the Snappy compressor:

https://github.com/xerial/snappy-java/issues/209
