### ISSUE TITLE
Backup of file fails if the cli is run from a directroy that user doesn't have permission

### ISSUE THREAD

**Issue by shambupujar** [radixdlt/node-runner#29]
Below is the exception thrown when user runs the cli is run from a directroy that user doesn't have permission

```
Node key file already exist at location /etc/radixdlt/node/secrets
Enter the password of the existing keystore file 'node-keystore.ks':
environment file exists. Do you want to back up [Y/n]:y
Traceback (most recent call last):
  File "radixnode.py", line 648, in <module>
  File "radixnode.py", line 226, in setup
  File "setup/SystemD.py", line 80, in backup_file
  File "pathlib.py", line 1268, in mkdir
PermissionError: [Errno 13] Permission denied: '2021_07_22_09_47'
[1671] Failed to execute script 'radixnode' due to unhandled exception!
```

**Comment by sullltan123** [comment]
👍
